# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af4fd55e5407520ac200d303837e73909c1b6212166261ace0f6295d4b96b4e3de064d03f3544b260c3415d7a36cc36b2ab5e4fd4dd91ebb783b48d70a885a3

test:
  secret_key_base: 7ccc54ef0476789ec39ec000f7435c67abbb514ab177c68d94a86dd813c442f1a0fe4a530cf6ab856637b8e4d9d76cbd324a313e77ca487660cc9065c708d280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
